### ISSUE TITLE
Caused error for jquery

### ISSUE THREAD

**Issue by SettingDust** [YS-Wong/Adaptive-Tab-Bar-Color#33] opened 2022-10-10 02:36 UTC
Show this when I login battlenet in china (seems different from other areas). It's fine when disable this addon
`Uncaught (in promise) Error: Permission denied to access property "apply"`

**Comment by YS-Wong** [comment] 2022-10-10 03:09
Duplicate of #30

**Closed** 2022-10-10 03:10 UTC
